<div class="w-xxxx-12 _my_cart _pt_header">
    <div class="content">
        <div class="w-xxxx-12 wrapper_white">
            <h1>Finalizar compra</h1>
            <div class='w-xxxx-9 contenedor_checkout'>
              
            <?php 
            
            if(!$MySession->LoggedIn()){
                $active_class='_active';
            ?>
                <div class="_mycart_step _cero">
                    <h2 class='datos_customer _tab_step _nono <?=$active_class?>'>Cuenta de usuario</h2>
                        <div>
                            <div class="w-xxxx-12">
                                <div class="w-xxxx-6 w-xxx-6 w-xx-12"><h3 class="align_center _btn_primary_rules_hover"><a href="#" class="checkout_cuenta_login">Inicias sesión</a></h3></div>
                                <div class="w-xxxx-6 w-xxx-6 w-xx-12"><h3 class="align_center _btn_primary_rules"><a href="#" class="checkout_cuenta_datos">Continuar como invitado</a></h3></div>
                            </div>
                        
                            <div class="frmlogin">
                                
                            <?=render("checkout/frm.login.phtml")?>
                            </div>
                            <div class="frmdatos">
                                <?=render("checkout/frm.customer.phtml")?>
                            </div>
                        </div>
                        <div id="resumen_datos_customer"></div>
                </div>
                <?php 
                $active_class = '';
            }
            else {
                $active_class='_active';
            }
            ?>

       
    
                <div class="_mycart_step _first <?=$active_class?>">
                    <h2 class='direccion_entrega _tab_step _nono <?=$active_class?>'>Dirección de entrega</h2>
                    <div style="display:<?=(empty($active_class) ? 'none' : '')?>;">
                      <?php if(isset($DireccionEnvioCheckoutForm)): ?>
                        <?php echo $DireccionEnvioCheckoutForm->openTag(); ?>
                        <?php echo $DireccionEnvioCheckoutForm->getRow("id_envio"); ?>
                        <label for="id_envio" class="error" style="display:none;"></label>
                        <?php echo $DireccionEnvioCheckoutForm->getRow("continuar"); ?>
                        <?php echo $DireccionEnvioCheckoutForm->endTag(); ?>
                      <?php endif; ?>
                        <div id="form_direccion_envio" style="display:<?= (isset($DireccionEnvioCheckoutForm) ? 'none' : ''); ?>;">
                            <?php echo $direccionesForm->openTag(); ?>
                            <?php echo $direccionesForm->getAllRow(); ?>
                            <?php echo $direccionesForm->endTag(); ?>
                        </div>
                       

                        
                    </div>
                    <div id="resumen_checkout_envio"></div>
                </div>
                <?php 
                $active_class = '';
                ?>

                <div class="_mycart_step _second">
                    <h2 class='direccion_facturacion _tab_step _nono  <?=$active_class?>'>Dirección de Facturación</h2>
                    <div style="display:<?=(empty($active_class) ? 'none' : '')?>;">
                        <?php echo $DireccionCheckoutForm->openTag(); ?>
                        <?php echo $DireccionCheckoutForm->getRow("id_facturacion"); ?>
                        <?php echo $DireccionCheckoutForm->getRow("continuar"); ?>
                        <label for="id_facturacion" class="error" style="display:none;"></label>
                        <?php echo $DireccionCheckoutForm->endTag(); ?>

                        <div id="form_direccion_facturacion" style="display:none;">
                            <?=render("checkout/frm.facturacion.phtml")?>
                        </div>
                    </div>
                    <div id="resumen_checkout_facturacion"></div>
                </div>

                <?php if($productos_comprados['envio_requerido'] == 1): ?>
                <div class="_mycart_step _third">

                    <h2 class='metodo_envio disabled _tab_step _nono'>Selecciona tu método de envio</h2>

                    <div id="content_metodo_envio" style="display:none;">
                        
                    </div>
                    <div id="resumen_metodo_envio"></div>
                </div>
                <?php endif; ?>

                <div class="_mycart_step fourth">

                    <h2 class='metodo_pago _tab_step _nono'>Selecciona tu método de pago</h2>

                    <div  id="content_metodo_pago" style="display:none;">
                       
                    </div>
                </div>



                <div class="_mycart_step fifth">
                    <h2 class='paga_ahora _tab_step _nono'>Paga tu pedido</h2>
                    <div id="contenedor_frm_pago">
                    </div>
                </div>
            </div>

            <div class="w-xxxx-3 _checkout_resume">                     
                    <h2>Resumen de compra</h2>
                    <?php foreach($productos_comprados['productos'] as $producto): ?>
                    <ul>
                     
                        <li><?php  echo makeHTMLImg($producto["img"],"","",$producto["nombre"],"class='img_100'"); ?><h3><?=$producto['nombre']; ?></h3></li>
                        <li>QTY: <span class="_x_number"><?=$producto['qty']; ?> </span><strong><?=$producto['precio'] ?></strong> </li>
                    </ul>
                    <?php endforeach; ?>
                    <?=render('carrito/frm.cupon.checkout.phtml')?>
                    <div class="_cont_resume_checkout">
                        <div class="_coin _checkout_subtotal"><strong>Subtotal</strong>: <span class="price"><?=$productos_comprados['subtotal']?></span></div>
                        <div class="_coin _checkout_iva"><strong>IVA</strong>: <span class="price"><?=$productos_comprados['iva']?></span></div>
                        <div class="_coin _checkout_envio" style="display:none;"><strong>Envio</strong>: <span class="price"></span></div>
                        <div class="_coin _checkout_descuento" <?=($productos_comprados['descuento'] > 0 ? '' : 'style="display:none;"')?>><strong>Descuento:</strong>: <span class="price"><?=$productos_comprados['descuento']?></span></div>
                        <div class="_coin _checkout_total"><strong>Total</strong>: <span class="price"><?=$productos_comprados['total']?></span></div>
                   </div>
            </div>

        </div>
    </div>
</div>


<script>
$(document).ready(function(){

    $( "#frm_direccion_envio" ).validate({
        submitHandler: function(form)
        {
             setDireccionCheckout();
             return false;
        }
    });

    $( "#frmdirecciones" ).validate({
        submitHandler: function(form)
        {
             setNuevaDireccionCheckout();
             return false;
        }
    });    


    $("input[name=id_envio]").change(function()
    {
        if($(this).val() == "otra")
        {
            $("#form_pick-up").hide();
            $("#form_direccion_envio").show();
            $("form[name=frm_direccion_envio] input[name=continuar]").hide();
        }
        else
        {
            $("#form_pick-up").hide();
            $("#form_direccion_envio").hide();
            $("form[name=frm_direccion_envio] input[name=continuar]").show();
        }
    })
});

$(document).ready(function(){

    $( "#frm_direccion" ).validate({
        submitHandler: function(form)
        {
             setFacturacionCheckout();
             return false;
        }
    });

    $( "#frmdirecciones_facturacion" ).validate({
        submitHandler: function(form)
        {
             setNuevaFacturacionCheckout();
             return false;
        }
    });

    $("input[name=id_facturacion]").change(function()
    {
       
        if($(this).val() == "otra")
        {
            $("#form_direccion_facturacion").show();
            $("form[name=frm_direccion] input[name=continuar]").hide();
        }
        else
        {
            $("#form_direccion_facturacion").hide();
            $("form[name=frm_direccion] input[name=continuar]").show();
        }
    })
});

$(".frmdatos").hide();
$(".checkout_cuenta_login").click(function(e){
    e.preventDefault();
    $(".frmdatos").hide();
    $(".frmlogin").show();
    $(".checkout_cuenta_datos").parent("h3").removeClass("_btn_primary_rules_hover");
    $(".checkout_cuenta_datos").parent("h3").addClass("_btn_primary_rules");
    $(".checkout_cuenta_login").parent("h3").addClass("_btn_primary_rules_hover");
    $(".checkout_cuenta_login").parent("h3").removeClass("_btn_primary_rules");
});
$(".checkout_cuenta_datos").click(function(e){
    e.preventDefault();
    $(".frmlogin").hide();
    $(".frmdatos").show();
    $(".checkout_cuenta_datos").parent("h3").addClass("_btn_primary_rules_hover");
    $(".checkout_cuenta_datos").parent("h3").removeClass("_btn_primary_rules");
    $(".checkout_cuenta_login").parent("h3").removeClass("_btn_primary_rules_hover");
    $(".checkout_cuenta_login").parent("h3").addClass("_btn_primary_rules");
});
    </script>