<div class="content">
<div class="w-xxxx-12">
    <?php echo breadcrumbs(); ?>
</div>


<div class="w-xxxx-8 m-l-xxxx-2 w-xxx-10  m-l-xxx-1 w-xx-12  m-l-xx-0 _card _m_t_30 imprimible_content">
    <h1>Detalle de pedido #<?=$detalle_pedido['order_id']?></h1>

    <div class="w-xxxx-12 cont_header_panel">
    <?php if($detalle_pedido['is_canceled'] == 0): ?>
        <?php if($detalle_pedido['is_shipping'] == 0): ?>
            <div class="_wrapp_form_serch">   
            <a href="#" class="shippingbtn">Enviar</a>
            </div>
          <?php endif; ?>
          <?php if($detalle_pedido['is_invoice'] == 0): ?>
          <div class="_wrapp_form_serch">
            <a href="#" class="invoicebtn">Facturar</a>
          </div>
          <?php endif; ?>
          <?php if($detalle_pedido['is_shipping'] == 0): ?>
            <div class="_wrapp_form_serch">
              <a href="#" class="cancelbtn">Cancelar</a>
            </div>
          <?php endif; ?>
      <?php endif; ?>
    </div>

    <div class="w-xxxx-6 w-xxx-6 w-xx-6 w-x-12"> 
      <ul class="_ul_txt_standar ">
        <li><strong>Estatus del pedido:</strong> <span class='set-status'><?=getLabelStatusTransaccion(DATA_STORE_CONFIG["id"], $detalle_pedido["state"],$detalle_pedido["status"])?></span></li> 
        <li><strong>Fecha:</strong> <?=$detalle_pedido['created_at'] ?></li>
          <li><strong >Cliente:</strong> <?=$detalle_pedido['name'] ?></li>
          <li><strong>E-mail:</strong> <?=$detalle_pedido['email']?></li>
          

      </ul>
      </div>
      <div class="w-xxxx-6 w-xxx-6 w-xx-6 w-x-12"> 

        <?php if(isset($detalle_pedido['shipping_address']) && !empty($detalle_pedido['shipping_address'])): ?>
          <?php if(!empty( $detalle_pedido['shipping_method'] )): ?>
            <h4>Datos del envio</h4>

            <ul class="_ul_txt_standar ">
              <li><strong>Metodo de envio:</strong> <?=getCoreConfig("ecommerce/".$detalle_pedido['shipping_method']."/titulo") ?></li>
            </ul>

            <?= getFormatreplace(getCoreConfig("ecommerce/ventas/address-format"),json_decode($detalle_pedido['shipping_address'],true)) ?>
          <?php endif; ?>
        <?php endif; ?>



        <?php if(isset($detalle_pedido['invoice_address']) && !empty($detalle_pedido['invoice_address'])): ?>
          <h4>Dirección de facturación</h4>
          <?= getFormatreplace(getCoreConfig("ecommerce/ventas/addressf-format"),json_decode($detalle_pedido['invoice_address'],true)) ?>
        <?php endif; ?>

      </div>
    <div class="order_content w-xxxx-12">
    <h4>Productos</h4>



    <div  class="w-xxxx-12 cont_gral_admin pedidos">
        <div class="w-xxxx-12">
            <div class="w-xxxx-12 contenedor_titulo_columnas">
              <div class="w-xxxx-3">Imagen</div>
              <div class="w-xxxx-3">Nombre</div>
              <div class="w-xxxx-3">QTY</div>
              <div class="w-xxxx-3">Total</div>
            </div>
        </div>
        <div class="contenedor_columnas_info"  >
      
    <?php foreach($detalle_pedido['productos'] as $producto): ?>
      <div class="w-xxxx-12 contenedor_columnas"  >
      <?php $thisClass  = ((($iRow % 2) == 0) ? "formFieldDk" : "formFieldLt");?>

        <div class="<?=$thisClass?> w-xxxx-3">
          <p><?=makeHTMLImg($producto['img'],50,50,$producto['nombre'])?></p>
        </div>
        <div class="<?=$thisClass?> w-xxxx-3">
                    
                                    <p><?php echo $producto['nombre']; ?></p>
                            

                                <?php if(!empty($producto['caracteristicas'])): ?>
                                        <ul class="caracteristicas">
                                        <?php foreach($producto['caracteristicas'] as $caracteristicas): ?>
                                          <?php if(!empty($caracteristicas['value'])): ?>
                                            <li><strong><?=$caracteristicas['name']?>:</strong><span><?=$caracteristicas['value']?></span></li>
                                            <?php endif ;?>
                                        <?php endforeach; ?>
                                        </ul>
                                    <?php endif; ?>

        </div>
        <div class="<?=$thisClass?> w-xxxx-3"><p><?php echo $producto['qty']; ?></p></div>
        <div class="<?=$thisClass?> w-xxxx-3"><p><?= $producto['total'] ?></p></div>

        </div>
    <?php endforeach; ?>

    
      </div>
    </div>
  </div>
</div>
    <div class="w-xxxx-8 m-l-xxxx-2 w-xxx-10  m-l-xxx-1 w-xx-12  m-l-xx-0 _card _m_t_30">

      <div class="w-xxxx-6  w-xxx-6 w-xx-6  w-x-12 ">
            <h3>Actualizaciones de la orden<h3>
        <?php if(!empty($logStatus)): ?>
        <?php foreach($logStatus as $status): ?>
        <ul>
          <li>Fecha: <?=$status['created_at']?></li>
          <li>Status: <?=$status['status']?></li>
          <?php if(!empty($status['comment'])): ?>
          <li><p><?=$status["comment"]?></p></li>
        <?php endif;?>
        
        </ul>
        <hr />
        <?php endforeach; ?>
        <?php else: ?>
          <p>Sin actualizaciones recientes</p>
          <hr />
        <?php endif; ?>
           
            <div class="w-xxxx-12  w-xxx-12 w-xx-12  w-x-12 ">
            <?=$StatusPagoForm->openTag()?>
            <?=$StatusPagoForm->get('order_id')?>
            <?=$StatusPagoForm->getRow('status')?>
            <div class="content_nota" >
            <?=$StatusPagoForm->getRow('comment')?>
            </div>
            <?=$StatusPagoForm->getRow('guardar')?>
            <?=$StatusPagoForm->endTag()?>
            <script >
            $(document).ready(function()
            {
                $('form[name=frmStatus').validate({

                    submitHandler: function(form)
                        {
                          SetStatusPagoEcommerce();
                          return false;
                        }
                });
            });
            </script>
            </div>
        </div>
        <div class="w-xxxx-6  w-xxx-6 w-xx-6  w-x-12 ">
          <h3>Informacion del pago<h3>

          <ul class="_ul_txt_standar ">
            <li><strong>Método de pago:</strong> <?=getCoreConfig("ecommerce/".$detalle_pedido['payment_method']."/name") ?></li>
            <li><?php $ObserverManager->dispatch('show_payment_data',["id" => $id]); ?></li>
            <li><strong>Descuento:</strong> <?=$detalle_pedido['discount'] ?></li>
            <li><strong>Total productos:</strong> <?=$detalle_pedido['totalItems']?></li>
            <li><strong>Monto envio:</strong> <?=$detalle_pedido['shippingPrice']?></li>
            <li><strong>Total a pagar:</strong> <?=$detalle_pedido['total']?></li>
            <li class="_total"><strong>Monto pagado:</strong> <?=$detalle_pedido['paymentTotal']?></li>
          </ul>
     

        </div>
    </div>
  </div>
</div>
<script type="text/javascript">
  window.ORDER_ID = "<?=$Tokenizer->token("order",$detalle_pedido["id"])?>";
</script>
<script>
  $(".cancelbtn").click(function(e){
    e.preventDefault();
    CancelOrder();
  });
</script>