<?php echo $MetodoEnvioCheckoutForm->openTag(); ?>
<?php echo $MetodoEnvioCheckoutForm->getRow("id_metodo_envio"); ?>
<label for="id_metodo_envio" class="error" style="display:none;"></label>

<?php 
unset($shippingMethodsHTML['codes']);
foreach($shippingMethodsHTML as $code => $shipping) {?>
    <div id="shipping_<?=$code?>" class="shipping_html" style="display:none;">
        <?=$shipping["html"]?>
    </div>
<? } ?>
<?php echo $MetodoEnvioCheckoutForm->getRow("continuar"); ?>
<?php echo $MetodoEnvioCheckoutForm->endTag(); ?>
<script>
$("input[name=id_metodo_envio]").change(function(){
    $(".shipping_html").hide();
    $('#shipping_'+$(this).val()).show();
});
</script>