<div class="w-xxxx-12">
    <?=$direccionesFacturacionForm->openTag(); ?>
    <?=$direccionesFacturacionForm->getRow('nombre')?>
    <?=$direccionesFacturacionForm->getRow('rfc')?>
    <?=$direccionesFacturacionForm->getRow('calle')?>
    <?=$direccionesFacturacionForm->getRow('numero')?>
    <?=$direccionesFacturacionForm->getRow('numeroi')?>
    <?=$direccionesFacturacionForm->getRow('cp')?>
    <?=$direccionesFacturacionForm->getRow('estado')?>
    <?=$direccionesFacturacionForm->getRow('ciudad')?>
    <?=$direccionesFacturacionForm->getRow('municipio')?>
    <?=$direccionesFacturacionForm->getRow('colonia')?>
    <?php 
    if ($MySession->LoggedIn()) {
        echo $direccionesFacturacionForm->getRow('save_address');
    }
    ?>

    <?=$direccionesFacturacionForm->getRow('guardar')?>
    <?=$direccionesFacturacionForm->endTag(); ?>
</div>
    