<div class="w-xxxx-12">
    <div class="w-xxxx-10">
        Calle <?=$direccion_facturacion['calle']?> #<?=$direccion_facturacion['numero']?>, Colonia <?=$direccion_facturacion['colonia']?>, municipio <?=$direccion_facturacion['municipio']?>,<?=$direccion_facturacion['pais']?> C.P. <?=$direccion_facturacion['cp']?>
        <br />
        RFC <?=$direccion_facturacion['RFC']?>
    </div>
    <div class="w-xxxx-2">
        <a href="javascript:void(0)" onclick="changeBillingAddress();"><i class="icon icon-editar"></i>Cambiar</a>
    </div>
    </div>
