<div class="w-xxxx-12">
    <div class="w-xxxx-10">
    <?php
    $direccionf = getCoreConfig("ecommerce/ventas/addressf-format");
    echo sprintf($direccionf,$direccion_facturacion["name"],$direccion_facturacion["rfc"],$direccion_facturacion["calle"],$direccion_facturacion["numero"],$direccion_facturacion["colonia"],$direccion_facturacion["municipio"],$direccion_facturacion["estado"],$direccion_facturacion["cp"]);
    ?>
    </div>
    <div class="w-xxxx-2">
        <a href="javascript:void(0)" onclick="changeBillingAddress();"><i class="icon icon-editar"></i>Cambiar</a>
    </div>
    </div>
