<div class="content">
<div class="w-xxxx-12">
    <?php echo breadcrumbs(); ?>
</div>


<div class="w-xxxx-8 m-l-xxxx-2 w-xxx-10  m-l-xxx-1 w-xx-12  m-l-xx-0 _card _m_t_30 imprimible_content">
    <h1>Detalle de pedido #<?=$detalle_pedido['order_id']?></h1>
    <div class="w-xxxx-6 w-xxx-6 w-xx-6 w-x-1"> 
      <ul class="_ul_txt_standar ">
        <li><strong>Fecha:</strong> <?=$detalle_pedido['created_at'] ?></li>
          <li><strong >Usuario:</strong> <?=$detalle_pedido['name'] ?></li>
          <li><strong>E-mail:</strong> #<?=$detalle_pedido['email']?></li>
          <li><strong>Método de pago:</strong> <?=$detalle_pedido['payment_method']?></li>
          <li><strong>Estatus de pago:</strong> <span class='set-status'><?php echo getStatusTransaccion($detalle_pedido['status']); ?></span></li>
          <li><strong>Monto envio:</strong> <?=$detalle_pedido['shippingPrice']?></li>
          <li><strong>Descuento:</strong> <?=$detalle_pedido['discount'] ?></li>
          <li><strong>Total productos:</strong> <?=$detalle_pedido['totalItems']?></li>
          <li><strong>Total a pagar:</strong> <?=$detalle_pedido['total']?></li>
          <li class="_total"><strong>Monto pagado:</strong> <?=$detalle_pedido['paymentTotal']?></li>
          <?php

          $referencia = json_decode($detalle_pedido['referencia'],true);
        
          ?>
          <?php if($detalle_pedido['metodo_pago'] == 'conekta_oxxo'): ?>
            <li>Referencia pago oxxo: <?=$referencia['referencia']?></li>
          <?php endif;?>
          <?php if($detalle_pedido['metodo_pago'] == 'openpay_establecimiento'): ?>
            <li>Codigo de pago: <?=makeHTMLImg($referencia['payment_method']['barcode_url'],150,'','codigo de barras pago');?></li>
            <li>Referencia pago: <?=$referencia['payment_method']['reference']?></li>
            <li>Fecha limite de pago: <?=getfechaUI($referencia['due_date'])?></li>
          <?php endif;?>
          <?php if($detalle_pedido['metodo_pago'] == 'srpago_oxxo'): ?>

          
            <?php $expiration_date = explode("T",$referencia['expiration_date']); ?>
            <li>Codigo de pago: <?=makeHTMLImg($referencia['barcode_url'],150,'','codigo de barras pago');?></li>
            <li>Referencia pago: <?=$referencia['barcode']?></li>
            <li>Fecha limite de pago: <?=getfechaUI($expiration_date[0])?></li>
          

          <?php endif;?>
          <?php if($detalle_pedido['metodo_pago'] == 'srpago_spei'): ?>

          <li>Referencia pago: <?=$referencia['order_id']?></li>
        
          <?php endif;?>
      </ul>
      </div>
      <div class="w-xxxx-6 w-xxx-6 w-xx-6 w-x-1"> 

        <?php if(isset($detalle_pedido['shipping_address']) && !empty($detalle_pedido['shipping_address'])): ?>
          <?php if(!empty( $detalle_pedido['shipping_method'] )): ?>
            <h4>Datos del envio</h4>
            <?= getFormatreplace(getCoreConfig("ecommerce/ventas/address-format"),json_decode($detalle_pedido['shipping_address'],true)) ?>
          <?php endif; ?>
        <?php endif; ?>



        <?php if(isset($detalle_pedido['invoice_address']) && !empty($detalle_pedido['invoice_address'])): ?>
          <h4>Dirección de facturación</h4>
          <?= getFormatreplace(getCoreConfig("ecommerce/ventas/addressf-format"),json_decode($detalle_pedido['invoice_address'],true)) ?>
        <?php endif; ?>

      </div>
    <div class="order_content">
    <h4>Productos</h4>



    <div  class="w-xxxx-12 cont_gral_admin pedidos">
        <div class="w-xxxx-12">
            <div class="w-xxxx-12 contenedor_titulo_columnas">
              <div class="w-xxxx-3">Imagen</div>
              <div class="w-xxxx-3">Nombre</div>
              <div class="w-xxxx-3">QTY</div>
              <div class="w-xxxx-3">Total</div>
            </div>
        </div>
        <div class="contenedor_columnas_info"  >
      
    <?php foreach($detalle_pedido['productos'] as $producto): ?>
      <div class="w-xxxx-12 contenedor_columnas"  >
      <?php $thisClass  = ((($iRow % 2) == 0) ? "formFieldDk" : "formFieldLt");?>

        <div class="<?=$thisClass?> w-xxxx-3">
          <p><?=makeHTMLImg($producto['img'],50,50,$producto['nombre'])?></p>
        </div>
        <div class="<?=$thisClass?> w-xxxx-3">
                    
                                    <p><?php echo $producto['nombre']; ?></p>
                            

                                <?php if(!empty($producto['caracteristicas'])): ?>
                                        <ul class="caracteristicas">
                                        <?php foreach($producto['caracteristicas'] as $caracteristicas): ?>
                                          <?php if(!empty($caracteristicas['value'])): ?>
                                            <li><strong><?=$caracteristicas['name']?>:</strong><span><?=$caracteristicas['value']?></span></li>
                                            <?php endif ;?>
                                        <?php endforeach; ?>
                                        </ul>
                                    <?php endif; ?>

        </div>
        <div class="<?=$thisClass?> w-xxxx-3"><p><?php echo $producto['qty']; ?></p></div>
        <div class="<?=$thisClass?> w-xxxx-3"><p><?= $producto['total'] ?></p></div>

        </div>
    <?php endforeach; ?>

    
      </div>
    </div>
  </div>
</div>

    <div class="w-xxxx-8 m-l-xxxx-2 w-xxx-10  m-l-xxx-1 w-xx-12  m-l-xx-0 _card _m_t_30">

          <h3>Actualizaciones de la orden<h3>
      <?php if(!empty($logStatus)): ?>
      <?php foreach($logStatus as $status): ?>
      <ul>
        <li>Fecha: <?=$status['created_at']?></li>
        <li>Status: <?=$status['status']?></li>
        <?php if(!empty($status['comment'])): ?>
        <li><p><?=$status["comment"]?></p></li>
      <?php endif;?>
      
      </ul>
      <hr />
      <?php endforeach; ?>
      <?php else: ?>
        <p>Sin actualizaciones recientes</p>
      <?php endif; ?>


    </div>
</div>